data_source:
  source: data/data/original_data.csv


cutoff:
  powerlaw: 272087.52
  onemill: 1000000


event:
  year: 2014
  month: 9
  day: 3

period: 6


processed_data:
  cutoff: data/data/cutoff_data.csv
  event_data: data/data/event_data.csv
  clustered_data: data/data/kmeans.csv
  labeled_data: data/data/labeled_data.csv
  featured_data: data/data/processed/featured_data.csv
  mistakes: data/data/confusion_matrix_diff.csv
  predicted: data/data/processed/all_data_classes.csv

clustering:
  no_clusters: 100
  random_state: 10
  cluster_example: 79
  company_example: 'PS0000270158'