data_source:
  source: data/original_data.csv


cutoff:
  powerlaw: 272087.52
  onemill: 1000000


event:
  year: 2014
  month: 9
  day: 3

period: 6


processed_data:
  cutoff: data/cutoff_data.csv
  event_data: data/event_data.csv
  clustered_data: data/kmeans.csv
  labeled_data: data/labeled_data.csv
  featured_data: data/processed/featured_data.csv
  predicted: data/processed/all_data_classes.csv