data_source:
  source: data/data/original_data.csv


cutoff:
  powerlaw: 272087.52
  onemill: 1000000


event:
  year: 2014
  month: 9
  day: 3

period: 6


processed_data:
  cutoff: data/data/cutoff_data.csv
  event_data: data/data/event_data.csv
  clustered_data: data/data/kmeans.csv
  labeled_data: data/data/labeled_data_no_dupl.csv
  featured_data: data/data/processed/featured_data.csv
  false_neg_pred: data/data/false_neg_predictions.csv
  false_pos_pred: data/data/false_pos_predictions.csv
  true_pred: data/data/true_predictions.csv
  predicted: data/data/all_predictions.csv

clustering:
  no_clusters: 100
  random_state: 10
  cluster_example: 79
  company_example: 'PS0000016037'